/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HighlightRouteImport } from './routes/highlight'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightRoute = HighlightRouteImport.update({
  id: '/highlight',
  path: '/highlight',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/api/proxy': typeof ApiProxyRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/api/proxy': typeof ApiProxyRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/api/proxy': typeof ApiProxyRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/welcome'
    | '/api/proxy'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/welcome'
    | '/api/proxy'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/search'
    | '/welcome'
    | '/api/proxy'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  HighlightRoute: typeof HighlightRoute
  HomeRoute: typeof HomeRoute
  InterestsRoute: typeof InterestsRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiProxyRoute: typeof ApiProxyRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlight': {
      id: '/highlight'
      path: '/highlight'
      fullPath: '/highlight'
      preLoaderRoute: typeof HighlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  HighlightRoute: HighlightRoute,
  HomeRoute: HomeRoute,
  InterestsRoute: InterestsRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  WelcomeRoute: WelcomeRoute,
  ApiProxyRoute: ApiProxyRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
