/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WatchingRouteImport } from './routes/watching'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HighlightRouteImport } from './routes/highlight'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiSendDigestsRouteImport } from './routes/api/send-digests'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiCheckWatchesRouteImport } from './routes/api/check-watches'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingRoute = WatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightRoute = HighlightRouteImport.update({
  id: '/highlight',
  path: '/highlight',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendDigestsRoute = ApiSendDigestsRouteImport.update({
  id: '/api/send-digests',
  path: '/api/send-digests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckWatchesRoute = ApiCheckWatchesRouteImport.update({
  id: '/api/check-watches',
  path: '/api/check-watches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watching': typeof WatchingRoute
  '/welcome': typeof WelcomeRoute
  '/api/check-watches': typeof ApiCheckWatchesRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/send-digests': typeof ApiSendDigestsRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watching': typeof WatchingRoute
  '/welcome': typeof WelcomeRoute
  '/api/check-watches': typeof ApiCheckWatchesRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/send-digests': typeof ApiSendDigestsRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/highlight': typeof HighlightRoute
  '/home': typeof HomeRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watching': typeof WatchingRoute
  '/welcome': typeof WelcomeRoute
  '/api/check-watches': typeof ApiCheckWatchesRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/send-digests': typeof ApiSendDigestsRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/admin'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/watching'
    | '/welcome'
    | '/api/check-watches'
    | '/api/proxy'
    | '/api/send-digests'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/admin'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/watching'
    | '/welcome'
    | '/api/check-watches'
    | '/api/proxy'
    | '/api/send-digests'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/admin'
    | '/highlight'
    | '/home'
    | '/interests'
    | '/login'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/setup'
    | '/terms'
    | '/watching'
    | '/welcome'
    | '/api/check-watches'
    | '/api/proxy'
    | '/api/send-digests'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdminRoute: typeof AdminRoute
  HighlightRoute: typeof HighlightRoute
  HomeRoute: typeof HomeRoute
  InterestsRoute: typeof InterestsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  WatchingRoute: typeof WatchingRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiCheckWatchesRoute: typeof ApiCheckWatchesRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiSendDigestsRoute: typeof ApiSendDigestsRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching': {
      id: '/watching'
      path: '/watching'
      fullPath: '/watching'
      preLoaderRoute: typeof WatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlight': {
      id: '/highlight'
      path: '/highlight'
      fullPath: '/highlight'
      preLoaderRoute: typeof HighlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-digests': {
      id: '/api/send-digests'
      path: '/api/send-digests'
      fullPath: '/api/send-digests'
      preLoaderRoute: typeof ApiSendDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-watches': {
      id: '/api/check-watches'
      path: '/api/check-watches'
      fullPath: '/api/check-watches'
      preLoaderRoute: typeof ApiCheckWatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdminRoute: AdminRoute,
  HighlightRoute: HighlightRoute,
  HomeRoute: HomeRoute,
  InterestsRoute: InterestsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  WatchingRoute: WatchingRoute,
  WelcomeRoute: WelcomeRoute,
  ApiCheckWatchesRoute: ApiCheckWatchesRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiSendDigestsRoute: ApiSendDigestsRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
